# Generated by Django 3.2.25 on 2026-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_asistencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='medio_pago',
            field=models.CharField(blank=True, default='Seleccione', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='rut',
            field=models.CharField(blank=True, default=999999, max_length=12, null=True),
        ),
    ]
