# Generated by Django 3.2.25 on 2026-01-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20260104_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(default=True),
        ),
    ]
