# Generated by Django 3.2.25 on 2026-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_asistencia_asistio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='medio_pago',
            field=models.CharField(default='Seleccione', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='Seleccione', max_length=100),
        ),
    ]
