# Generated by Django 3.2.25 on 2026-01-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20260116_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='medio_pago',
            field=models.CharField(default='Seleccionar', max_length=20),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='pago_diario',
            field=models.IntegerField(default=0, help_text='Monto acordado por día trabajado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(default='Seleccionar', max_length=100),
        ),
    ]
