# Generated by Django 3.2.25 on 2026-01-10 20:45

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='nombre_tienda',
            field=models.CharField(blank=True, default='empy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='empy', editable=False, null=True, populate_from='nombre_tienda'),
        ),
    ]
