# Generated by Django 3.2.25 on 2026-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20260110_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='nombre_tienda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
