# Generated by Django 3.2.25 on 2026-01-10 22:59

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_usermetadata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermetadata',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='empy', editable=False, null=True, populate_from='nombre_tienda'),
        ),
    ]
