# Generated by Django 3.2.25 on 2026-01-11 19:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_usermetadata_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermetadata',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre_tienda'),
        ),
    ]
