# Generated by Django 3.2.25 on 2026-01-14 21:26

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0006_alter_usermetadata_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_tienda', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Solo letras y números.', regex='^[a-zA-Z0-9]+$')])),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='nombre_tienda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserStore',
                'verbose_name_plural': 'UsersStore',
                'db_table': 'users_store',
            },
        ),
        migrations.DeleteModel(
            name='UserMetaData',
        ),
    ]
